import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import DotGrid from "../components/DotGrid";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable}  antialiased bg-[#111111] text-[#dddddd]`}
      >
        <div
          style={{
            position: "relative",
            minHeight: "100vh",
          }}
        >
          {/* DotGrid background */}
          <div
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              width: "100%",
              height: "100%",
              zIndex: 5,
            }}
          >
            <DotGrid
              dotSize={2}
              gap={25}
              baseColor="#1B1B1B"
              proximity={0}
              shockRadius={250}
              shockStrength={5}
              resistance={750}
              returnDuration={1.5}
            />
          </div>
          {/* Page content */}
          <div className="relative max-w-7xl mx-auto z-20">{children}</div>
        </div>
      </body>
    </html>
  );
}
